# Generated by Django 4.1.2 on 2022-12-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_title_categoryblog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryblog',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Категория'),
        ),
    ]
