# Generated by Django 4.1.2 on 2022-12-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='counter_ip_readers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(to='blog.counter_ip_readers', verbose_name='Кол-во уникальных просмотров'),
        ),
    ]
