# Generated by Django 4.1.2 on 2022-12-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_counter_ip_readers_remove_post_views_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
