# Generated by Django 4.0.2 on 2022-02-24 14:01

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, verbose_name='слаг на английском, например "Category"')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shop.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
                'ordering': ('tree_id', 'level'),
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Производитель')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_product', to='shop.category')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('type_motor', models.CharField(blank=True, choices=[('VINT', 'Винт'), ('VODOMET', 'Водомет'), ('NET', 'Нет')], max_length=7, verbose_name='Тип мотора')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='Длинна см')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина см')),
                ('cockpit_length', models.IntegerField(blank=True, null=True, verbose_name='Длинна кокпита см')),
                ('cockpit_width', models.IntegerField(blank=True, null=True, verbose_name='Ширина кокпита см')),
                ('cylinder_diameter', models.IntegerField(blank=True, null=True, verbose_name='Диаметр борта см')),
                ('fabric_thickness_bottom', models.IntegerField(blank=True, null=True, verbose_name='Плотность ткани дна (г/м²)')),
                ('fabric_thickness_side', models.IntegerField(blank=True, null=True, verbose_name='Плотность ткани борта (г/м²)')),
                ('inflatable_compartments', models.IntegerField(blank=True, null=True, verbose_name='Количество надувных отсеков')),
                ('load_capacity', models.IntegerField(blank=True, null=True, verbose_name='Грузоподъемность кг')),
                ('passenger_capacity', models.IntegerField(blank=True, null=True, verbose_name='Пассажировместимость чел')),
                ('maximum_motor_power', models.IntegerField(blank=True, null=True, verbose_name='Макс мощность мотора лс')),
                ('boat_weight', models.IntegerField(blank=True, null=True, verbose_name='Вес лодки кг')),
                ('complete_set_weight', models.IntegerField(blank=True, null=True, verbose_name='Вес полного комплекта кг')),
                ('bulwark', models.BooleanField(blank=True, default=False, verbose_name='Фальшборт')),
                ('keel', models.BooleanField(blank=True, default=False, verbose_name='Киль')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.color', verbose_name='Цвет лодки')),
            ],
            options={
                'verbose_name': 'Лодка',
                'verbose_name_plural': 'Лодки',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='VideosBoats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=100, verbose_name='Ссылка на видеоролик')),
                ('boat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.boat', verbose_name='Лодка')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.reviews', verbose_name='Родитель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.boat', verbose_name='Лодка')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Photo_boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='photo/', verbose_name='Изображение')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodimg', to='shop.boat', verbose_name='Лодка')),
            ],
            options={
                'verbose_name': 'Фото лодки',
                'verbose_name_plural': 'Фото Лодок',
            },
        ),
    ]

