# Generated by Django 4.0.2 on 2022-02-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_boat_color_remove_boat_price_product_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='photo/', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodimg', to='shop.product', verbose_name='')),
            ],
            options={
                'verbose_name': 'Фото лодки',
                'verbose_name_plural': 'Фото Лодок',
            },
        ),
        migrations.CreateModel(
            name='VideosProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=100, verbose_name='Ссылка на видеоролик')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.boat', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.RemoveField(
            model_name='videosboats',
            name='boat',
        ),
        migrations.DeleteModel(
            name='Photo_boat',
        ),
        migrations.DeleteModel(
            name='VideosBoats',
        ),
    ]
